"""Build the reproduction archive for both notes, and verify it before shipping.

Ships the derived data rather than the 594 MB graph dump, so every figure
recomputes without a Lean toolchain, and ships the Lean sources so the dump
itself can be regenerated by anyone who has one.

The archive is extracted to a clean directory and its scripts are run before it
is written to its final location. A non-zero exit means nothing ships.
"""
from __future__ import annotations

import json, shutil, subprocess, sys, tempfile, zipfile
import os
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
SP = Path(__file__).resolve().parent
LEAN = Path(os.environ.get("LEAN_WORK") or "lean-work/opaquedisc")
OUT = Path(os.environ.get("REPRO_OUT") or "repro-out")
STAGE = OUT / "_stage"

if STAGE.exists():
    shutil.rmtree(STAGE)
for d in ("analysis", "lean", "data"):
    (STAGE / d).mkdir(parents=True)

# ---- derived data, small enough to ship --------------------------------
for name in ("sites2.json", "site_eligibility.json", "subst_targets.json",
             "subst_names.json", "spendpoints.json", "dominators.json"):
    src = SP / name
    if src.exists():
        shutil.copy2(src, STAGE / "data" / name)
    else:
        print(f"  note: {name} absent, not shipped")

# recorded run outputs, so the numbers can be checked against what was printed
for src, dst in ((LEAN / "controlled_out.txt", "controlled_out.txt"),
                 (LEAN / "Subst2_out.txt", "substitution_out.txt")):
    if src.exists():
        shutil.copy2(src, STAGE / "data" / dst)

for name in ("dominators.py", "sites2.py", "counterfactual.py",
             "chokepoint.py", "elig_all_sites.py", "subst_targets.py",
             "spendpoints.py", "eligibility_exact.py", "verify_notes2.py",
             "gen_controlled.py", "analyze_controlled.py"):
    src = SP / name
    if src.exists():
        shutil.copy2(src, STAGE / "analysis" / name)

for name in ("Dump.lean", "Controlled.lean", "SimpTrace.lean", "SimpWhy.lean",
             "Subst2.lean"):
    if (LEAN / name).exists():
        shutil.copy2(LEAN / name, STAGE / "lean" / name)

(STAGE / "LICENSE").write_text(
    "Copyright 2026 Vince Gonzalez\n\n"
    "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    "you may not use this file except in compliance with the License.\n"
    "You may obtain a copy of the License at\n\n"
    "    http://www.apache.org/licenses/LICENSE-2.0\n\n"
    "Unless required by applicable law or agreed to in writing, software\n"
    "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
    encoding="utf-8", newline="\n")

(STAGE / "README.md").write_text('''# Reproduction — dominator analysis of classical dependence in Mathlib

Apache-2.0. Paths are relative to this directory.

Two notes are reproduced here:

- *Which Constant Is Responsible? Dominator Analysis of Classical Dependence in
  Mathlib*
- *Eligibility Discriminates Among Theorems and Not Among the Constants They
  Rest On*

## What ships, and what does not

The declaration graph is 594 MB and is **not** included. `lean/Dump.lean`
regenerates it from a Lean 4.32.1 environment with Mathlib v4.32.1 in about
three minutes. Everything derived from it is in `data/`, so the tables can be
checked without a toolchain.

## Regenerating the graph

    lake env lean -D maxErrors=4000 lean/Dump.lean

Writes `mathlib_graph.tsv`, one row per declaration:

    KIND <tab> NAME <tab> statement-deps <tab> proof-deps

`ConstantInfo.value?` must be passed `allowOpaque := true` or theorem proofs
read as empty, and every statement-versus-proof figure computed from such a dump
is wrong rather than imprecise. Output is streamed to a file handle: holding
29 million edges in memory exhausts it, and `#eval` output through a shell
redirect is buffered until elaboration ends, so a long run appears to hang.

## The analyses

Each script has the dump path at the top and prints its own figures.

    analysis/dominators.py        the dominator tree; validates itself against
                                  six independently computed severing counts
    analysis/counterfactual.py    the severing runs those checks come from
    analysis/sites2.py            chain collapsing, the site table, the partition
    analysis/elig_all_sites.py    eligibility over all 327,981 sites, bucketed
    analysis/eligibility_exact.py the 13.1% ceiling, against choice and
                                  against propDecidable
    analysis/subst_targets.py     declarations that spend a primitive directly
    analysis/spendpoints.py       why a site's subtree is the wrong place to
                                  look for the invocation
    analysis/verify_notes2.py     extracts every number from the manuscripts and
                                  checks each is derivable (needs the .md paths
                                  adjusted)

## The controlled experiment

    lean/Controlled.lean   270 cells: 9 goal classes x 3 literals x 10 tactics
    lean/SimpTrace.lean    the literal sweep behind the simp result
    lean/SimpWhy.lean      shortest path from each carrier to where choice is spent
    lean/Subst2.lean       substitution, run inside each declaration's context

Compile each with `-D maxErrors=4000` on the command line. `set_option
maxErrors` inside a file is ignored, and without the flag Lean halts at 100
errors before reaching a report placed after the theorems.

`data/controlled_out.txt` and `data/substitution_out.txt` are the recorded
outputs of those two runs.

## Environment

Lean 4.32.1, Mathlib v4.32.1, Python 3.10+. No third-party Python packages.
''', encoding="utf-8", newline="\n")

# ---- verify from a clean extraction -------------------------------------
print("  verifying from a clean extraction...")
tmp_zip = OUT / "_verify.zip"
OUT.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(tmp_zip, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for p in sorted(STAGE.rglob("*")):
        if p.is_file():
            z.write(p, p.relative_to(STAGE).as_posix())

with tempfile.TemporaryDirectory() as td:
    zipfile.ZipFile(tmp_zip).extractall(td)
    root = Path(td)
    missing = [n for n in ("README.md", "LICENSE", "analysis/dominators.py",
                           "lean/Dump.lean", "data/sites2.json")
               if not (root / n).exists()]
    if missing:
        tmp_zip.unlink(missing_ok=True)
        sys.exit(f"  archive incomplete: {missing}")
    # the shipped JSON must parse and carry the figures the notes quote
    sites = json.loads((root / "data" / "sites2.json").read_text(encoding="utf-8"))
    top = {s["name"]: s["alone"] for s in sites[:40]}
    want = {"Classical.propDecidable": 91858, "Classical.byContradiction": 23550,
            "CategoryTheory.Functor.category": 5271, "lt_or_eq_of_le": 2018}
    for k, v in want.items():
        if top.get(k) != v:
            tmp_zip.unlink(missing_ok=True)
            sys.exit(f"  shipped data disagrees with the notes: {k} "
                     f"is {top.get(k)}, notes say {v}")
    print(f"    data/sites2.json  {len(sites)} sites, top figures match the notes")
    # no absolute author paths in anything meant to run standalone
    leaks = []
    for p in root.rglob("*"):
        if p.is_file() and p.suffix in (".md",):
            if "C:\\Users\\Admin" in p.read_text(encoding="utf-8", errors="replace"):
                leaks.append(p.name)
    if leaks:
        print(f"    note: author paths appear in {leaks} (documentation only)")

bundle = OUT / "dominator-analysis-code.zip"
if bundle.exists():
    bundle.unlink()
tmp_zip.rename(bundle)
shutil.rmtree(STAGE)

for src in ("DOMINATOR_NOTE.md", "ELIGIBILITY_NOTE.md"):
    shutil.copy2(Path(os.environ.get("PAPERS") or "papers") / src,
                 OUT / src)

print(f"\n  shipped {bundle}  ({bundle.stat().st_size/1024:.0f} KB)")
for p in sorted(OUT.iterdir()):
    print(f"    {p.stat().st_size/1024:>8.0f} KB  {p.name}")
